language: python
sudo: false

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
      - mongodb-org-shell

services:
  - mongodb

branches:
  except:
    - /^feature/.*$/

python:
  - pypy
  - pypy3
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

#env:
#  - ACCELERATED=0
#  - ACCELERATED=1

install: travis_retry .travis/install.sh

script: tox

notifications:
  irc:
    channels:
      - 'irc.freenode.org#webcore'
    use_notice: true
    skip_join: true
